parcial20/parcial20/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path
from dubai import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.inicio, name='inicio'),
    path('agregar_registro/', views.agregar_registro, name='agregar_registro'),
    path('agregar_reserva/', views.agregar_reserva, name='agregar_reserva'),
    path('eliminar_registro/<int:id>/',
         views.eliminar_registro, name='eliminar_registro'),
    path('eliminar_reserva/<int:id>/',
         views.eliminar_reserva, name='eliminar_reserva'),
    # Ruta URL para la vista 'login'
    path('accounts/login/', views.iniciar_sesion, name='login'),
    # Ruta URL para la vista 'reg_user'
    path('reg_user/', views.reg_user, name='reg_user'),
    path('registro/', views.registro, name='registro'),
    path('blog/', views.blog, name='blog'),
    path('reserva/', views.reserva, name='reserva'),
    path('crear_viaje/', views.crear_viaje, name='crear_viaje'),
    path('viaje/', views.viaje, name='viaje'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
]

parcial20/dubai/models.py
from django.db import models
from django.utils import timezone


class Viaje(models.Model):
    destino = models.CharField(max_length=100, default="Untitled Trip")
    descripcion = models.TextField(default=timezone.now)
    fecha_llegada = models.DateField()
    hora_llegada = models.TimeField()
    fecha_salida = models.DateField()
    hora_salida = models.TimeField()
    lugar_salida = models.CharField(max_length=100)
    lugar_llegada = models.CharField(max_length=100)
    espacios_vigentes = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.destino} - {self.lugar_salida} a {self.lugar_llegada}"


class Registro(models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    edad = models.IntegerField()
    correo_electronico = models.EmailField()
    sexo = models.CharField(max_length=20)
    numero_telefono = models.CharField(max_length=10)
    destino = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"


class Reserva(models.Model):
    nombre = models.CharField(max_length=200)
    apellidos = models.CharField(max_length=200)
    edad = models.IntegerField()
    correo_electronico = models.EmailField()
    sexo = models.CharField(max_length=20)
    destino = models.CharField(max_length=200)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    cantidad_adultos = models.IntegerField(default=1)
    cantidad_menores = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.nombre} {self.apellidos} - {self.destino}"

parcial20/dubai/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .formulario.RegistroForm import RegistroForm
from .formulario.ReservaForm import ReservaForm
from .formulario.ViajeForm import ViajeForm
from .formulario.LoginForm import LoginForm
from .formulario.Re_userForm import NewUserForm
from .models import Registro, Reserva, Viaje


def reg_user(request):
    if request.method == "POST":
        formulario = NewUserForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/")
    else:
        formulario = NewUserForm()
    return render(request, "Reg_user.html", {"form": formulario})


def iniciar_sesion(request):
    if request.method == 'POST':
        formulario = LoginForm(request, data=request.POST)
        if formulario.is_valid():
            username = formulario.cleaned_data['username']
            password = formulario.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('inicio')
            else:
                messages.error(
                    request, "Usuario o contraseña incorrectos. Intente de nuevo.")
    else:
        formulario = LoginForm()
    return render(request, 'login.html', {'form': formulario})


def cerrar_sesion(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')
def home(request):
    es_estudiante = request.user.groups.filter(name='Estudiante').exists()
    es_admin = request.user.is_staff
    return render(request, 'index.html', {'user': request.user, 'es_estudiante': es_estudiante, 'es_admin': es_admin})


def index(request):
    registros = Registro.objects.all()
    reservas = Reserva.objects.all()
    viajes = Viaje.objects.all()
    return render(request, 'index.html', {'registros': registros, 'reservas': reservas, 'viajes': viajes})


def registro(request):
    registros = Registro.objects.all()
    return render(request, 'registro.html', {'registros': registros})


@login_required
def agregar_registro(request):
    if request.method == "POST":
        formulario = RegistroForm(request.POST)
        if formulario.is_valid():
            registro = formulario.save()  # Guarda el formulario y obtén el objeto de registro
            # Redirige a la página de registro después de guardar un registro
            return HttpResponseRedirect("/registro")
    else:
        formulario = RegistroForm()
    return render(request, "agregar_registro.html", {"form": formulario})


def reserva(request):
    reservas = Reserva.objects.all()
    return render(request, 'reserva.html', {'reservas': reservas})


@login_required
def agregar_reserva(request):
    if request.method == "POST":
        formulario = ReservaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect("/reserva")
    else:
        formulario = ReservaForm()
    return render(request, "agregar_reserva.html", {"form": formulario})


def eliminar_registro(request, id):
    Registro.objects.get(id=id).delete()
    return HttpResponseRedirect(request.path_info)


def eliminar_reserva(request, id):
    Reserva.objects.get(id=id).delete()
    return HttpResponseRedirect(request.path_info)


@login_required
def crear_viaje(request):
    if request.method == "POST":
        formulario = ViajeForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            # Redirige a la vista deseada después de guardar el viaje
            return HttpResponseRedirect("/viaje")
    else:
        formulario = ViajeForm()

    return render(request, 'crear_viaje.html', {'form': formulario})


def viaje(request):
    viajes = Viaje.objects.all()
    return render(request, 'viaje.html', {'viajes': viajes})


def blog(request):
    # Lógica de la vista del blog aquí
    return render(request, 'blog.html')


def inicio(request):
    # Tu lógica de vista aquí
    return render(request, 'index.html')

parcial20/dubai/templates/Reg_user.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #eceff1;
            color: #000000;
            font-family: Arial, sans-serif;
        }
        .navbar {
            background-color: #333;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: white;
        }
        .navbar ul {
            list-style: none;
            display: flex;
            gap: 20px;
            margin: 0;
        }
        .navbar ul li a {
            color: white;
            text-decoration: none;
        }
        .registro-container {
            width: 600px;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a style="color: white; text-decoration: none; font-size: 24px;">Agencia de Turismo VEN A DUBAI</a>
        <ul>
            <li><a href="{% url 'inicio' %}" style="color: white; text-decoration: none;">Principal</a></li>
            <li><a href="{% url 'agregar_registro' %}" style="color: white; text-decoration: none;">Agregar Registro</a></li>
            <li><a href="{% url 'registro' %}" style="color: white; text-decoration: none;">Registro</a></li>
            <li><a href="{% url 'agregar_reserva' %}" style="color: white; text-decoration: none;">Agregar Reserva</a></li>
            <li><a href="{% url 'reserva' %}" style="color: white; text-decoration: none;">Reserva</a></li>
            <li><a href="{% url 'blog' %}" style="color: white; text-decoration: none;">Blog</a></li>
            <li><a href="{% url 'login' %}" style="color: white; text-decoration: none;">Login</a></li>
            <li><a href="{% url 'crear_viaje' %}" style="color: white; text-decoration: none;">Crear Viaje</a></li>
            <li><a href="{% url 'viaje' %}" style="color: white; text-decoration: none;">Viaje</a></li>
        </ul>
    </div>
    <div class="reguser-container">
        <h1>Registro de Usuario</h1>
            <form method="POST" action="{% url 'reg_user' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Registrarse</button>
            </form>
    </div>
</body>
</html>

parcial20/dubai/templates/agregar_registro.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Registro</title>
    <style>
        body {
            background-color: #eceff1;
            color: #000000;
            font-family: Arial, sans-serif;
        }
        .navbar {
            background-color: #333;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: white;
        }
        .navbar ul {
            list-style: none;
            display: flex;
            gap: 20px;
            margin: 0;
        }
        .navbar ul li a {
            color: white;
            text-decoration: none;
        }
        .registro-container {
            width: 600px;
            margin: 0 auto;
        }
        
        .registro-form {
            background-color: #FFFFFF;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        
        .registro-form .form-group {
            margin-bottom: 20px;
        }
        
        .registro-form input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a style="color: white; text-decoration: none; font-size: 24px;">Agencia de Turismo VEN A DUBAI</a>
        <ul>
            <li><a href="{% url 'inicio' %}" style="color: white; text-decoration: none;">Principal</a></li>
            <li><a href="{% url 'registro' %}" style="color: white; text-decoration: none;">Registro</a></li>
            <li><a href="{% url 'agregar_reserva' %}" style="color: white; text-decoration: none;">Agregar Reserva</a></li>
            <li><a href="{% url 'reserva' %}" style="color: white; text-decoration: none;">Reserva</a></li>
            <li><a href="{% url 'blog' %}" style="color: white; text-decoration: none;">Blog</a></li>
            <li><a href="{% url 'login' %}" style="color: white; text-decoration: none;">Login</a></li>
            <li><a href="{% url 'reg_user' %}" style="color: white; text-decoration: none;">Registro usuario</a></li>
            <li><a href="{% url 'crear_viaje' %}" style="color: white; text-decoration: none;">Crear Viaje</a></li>
            <li><a href="{% url 'viaje' %}" style="color: white; text-decoration: none;">Viaje</a></li>
        </ul>
    </div>
    {% if user.is_staff %}
    <div class="registro-container">
        <h1>Agregar Registro</h1>
        <form class="registro-form" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" id="nombre" name="nombre" required>
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" id="apellidos" name="apellidos" required>
            </div>
            <div class="form-group">
                <label for="edad">Edad</label>
                <input type="number" id="edad" name="edad" required>
            </div>
            <div class="form-group">
                <label for="correo_electronico">Correo Electrónico</label>
                <input type="email" id="correo_electronico" name="correo_electronico" required>
            </div>
            <div class="form-group">
                <label for="sexo">Sexo</label>
                <div class="radio-group">
                    <input type="radio" id="masculino" name="sexo" value="masculino" required>
                    <label for="masculino">Masculino</label>
                </div>
                <div class="radio-group">
                    <input type="radio" id="femenino" name="sexo" value="femenino" required>
                    <label for="femenino">Femenino</label>
                </div>
            </div>
            <div class="form-group">
                <label for="numero_telefono">Número de Teléfono</label>
                <input type="tel" id="numero_telefono" name="numero_telefono" required>
            </div>
            <div class="form-group">
                <label for="destino">Destino</label>
                <input type="text" id="destino" name="destino" required>
            </div>
            <div class="form-group">
                <button type="submit">Registrar</button>
            </div>
        </form>
    </div>
    {% endif %}
</body>
</html>

parcial20/dubai/templates/agregar_reserva.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #eceff1;
            color: #000000;
            font-family: Arial, sans-serif;
        }
        .navbar {
            background-color: #333;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: white;
        }
        .navbar ul {
            list-style: none;
            display: flex;
            gap: 20px;
            margin: 0;
        }
        .navbar ul li a {
            color: white;
            text-decoration: none;
        }
        .reserva-container {
            width: 600px;
            margin: 0 auto;
        }
        .reserva-form {
            background-color: #FFFFFF;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .reserva-form h2 {
            margin-top: 0;
        }
        .reserva-form label {
            display: block;
            margin-bottom: 10px;
        }
        .reserva-form input[type="text"],
        .reserva-form input[type="number"],
        .reserva-form input[type="email"],
        .reserva-form select,
        .reserva-form input[type="date"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .reserva-form input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .reserva-form input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a style="color: white; text-decoration: none; font-size: 24px;">Agencia de Turismo VEN A DUBAI</a>
        <ul>
            <li><a href="{% url 'inicio' %}" style="color: white; text-decoration: none;">Principal</a></li>
            <li><a href="{% url 'registro' %}" style="color: white; text-decoration: none;">Registro</a></li>
            <li><a href="{% url 'agregar_registro' %}" style="color: white; text-decoration: none;">Agregar Registro</a></li>
            <li><a href="{% url 'reserva' %}" style="color: white; text-decoration: none;">Reserva</a></li>
            <li><a href="{% url 'blog' %}" style="color: white; text-decoration: none;">Blog</a></li>
            <li><a href="{% url 'login' %}" style="color: white; text-decoration: none;">Login</a></li>
            <li><a href="{% url 'reg_user' %}" style="color: white; text-decoration: none;">Registro usuario</a></li>
            <li><a href="{% url 'crear_viaje' %}" style="color: white; text-decoration: none;">Crear Viaje</a></li>
            <li><a href="{% url 'viaje' %}" style="color: white; text-decoration: none;">Viaje</a></li>
        </ul>
    </div>
    {% if user.is_staff %}
    <div class="reserva-container">
        <h1>Agregar Reserva</h1>
        <form class="reserva-form" method="POST">
            {% csrf_token %}
            <h2>Información de la Reserva</h2>
            <label for="id_nombre">Nombre:</label>
            <input type="text" id="id_nombre" name="nombre">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" id="id_apellidos" name="apellidos">
            <label for="id_edad">Edad:</label>
            <input type="number" id="id_edad" name="edad">
            <label for="id_correo_electronico">Correo Electrónico:</label>
            <input type="email" id="id_correo_electronico" name="correo_electronico">
            <label for="id_sexo">Sexo:</label>
            <select id="id_sexo" name="sexo">
                <option value="M">Masculino</option>
                <option value="F">Femenino</option>
            </select>
            <label for="id_destino">Destino:</label>
            <input type="text" id="id_destino" name="destino">
            <label for="id_fecha_inicio">Fecha de Inicio:</label>
            <input type="date" id="id_fecha_inicio" name="fecha_inicio" required>
            <label for="id_fecha_fin">Fecha de Fin:</label>
            <input type="date" id="id_fecha_fin" name="fecha_fin" required>
            <label for="id_cantidad_adultos">Cantidad de Adultos:</label>
            <input type="number" id="id_cantidad_adultos" name="cantidad_adultos">
            <label for="id_cantidad_menores">Cantidad de Menores:</label>
            <input type="number" id="id_cantidad_menores" name="cantidad_menores">
            <input type="submit" value="Guardar">
        </form>
    </div>
    {% endif %}
</body>
</html>
  

parcial20/dubai/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container">
    <nav>
        <div class="nav-wrapper">
        <a href="#" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'inicio' %}">Inicio</a></li>
            <li><a href="{% url 'registro' %}">Registro</a></li>
            <li><a href="{% url 'blog' %}">Blog</a></li>
        </ul>
        </div>
    </nav>
    <h1>Blog</h1>
    <div class="blog-post">
        <h2>Título del artículo</h2>
        <p>Contenido del artículo.</p>
    </div>
    <div class="blog-post">
        <h2>Título del artículo</h2>
        <p>Contenido del artículo.</p>
    </div>
    <div class="blog-post">
        <h2>Título del artículo</h2>
        <p>Contenido del artículo.</p>
    </div>
    <footer>
        <p>Pie de página</p>
    </footer>
</div>
<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

parcial20/dubai/templates/crear_viaje.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            background-color: #eceff1;
            color: #000000;
            font-family: Arial, sans-serif;
        }
        .navbar {
            background-color: #333;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            color: white;
        }
        .navbar ul {
            list-style: none;
            display: flex;
            gap: 20px;
            margin: 0;
        }
        .navbar ul li a {
            color: white;
            text-decoration: none;
        }
        .formulario {
            width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 5px;
        }
        .formulario h1 {
            text-align: center;
        }
        .formulario label {
            display: block;
            margin-bottom: 10px;
        }
        .formulario input[type="text"],
        .formulario textarea {
            width: 100%;
            padding: 5px;
            border: 1px solid #CCCCCC;
            border-radius: 3px;
        }
        .formulario button[type="submit"] {
            background-color: #4CAF50;
            color: #FFFFFF;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <a>Agencia de Turismo VEN A DUBAI</a>
        <ul>
            <li><a href="{% url 'inicio' %}">Principal</a></li>
            <li><a href="{% url 'agregar_registro' %}">Agregar Registro</a></li>
            <li><a href="{% url 'registro' %}">Registro</a></li>
            <li><a href="{% url 'agregar_reserva' %}">Agregar Reserva</a></li>
            <li><a href="{% url 'reserva' %}">Reserva</a></li>
            <li><a href="{% url 'blog' %}">Blog</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'reg_user' %}">Registro usuario</a></li>
            <li><a href="{% url 'viaje' %}">Viaje</a></li>
        </ul>
    </div>
    {% if user.is_staff %}
    <div class="formulario">
        <h1>Crear Viaje</h1>
        <form method="POST" action="{% url 'crear_viaje' %}">
            {% csrf_token %}
            <label for="destino">Destino:</label>
            <input type="text" id="destino" name="destino" required>
            <label for="descripcion">Descripción:</label>
            <textarea id="descripcion" name="descripcion" required></textarea>
            <label for="fecha_llegada">Fecha de Llegada:</label>
            <input type="date" id="fecha_llegada" name="fecha_llegada" required>
            <label for="hora_llegada">Hora de Llegada:</label>
            <input type="time" id="hora_llegada" name="hora_llegada" required>
            <label for="fecha_salida">Fecha de Salida:</label>
            <input type="date" id="fecha_salida" name="fecha_salida" required>
            <label for="hora_salida">Hora de Salida:</label>
            <input type="time" id="hora_salida" name="hora_salida" required>
            <label for="lugar_salida">Lugar de Salida:</label>
            <input type="text" id="lugar_salida" name="lugar_salida" required>
            <label for="lugar_llegada">Lugar de Llegada:</label>
            <input type="text" id="lugar_llegada" name="lugar_llegada" required>
            <label for="espacios_vigentes">Espacios Vigentes:</label>
            <input type="number" id="espacios_vigentes" name="espacios_vigentes" required>
            <button type="submit">Crear Viaje</button>
        </form>
    </div>
    {% endif %}
</body>
</html>

parcial20/dubai/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VEN A DUBAI</title>
</head>
<body>
  <div style="background-color: #f2f2f2; padding: 20px;">
    <nav style="background-color: #333; color: white; padding: 10px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <a  style="color: white; text-decoration: none; font-size: 24px;">Agencia de Turismo VEN A DUBAI</a>
          <ul style="list-style: none; display: flex; gap: 20px; margin: 0;">
            <li><a href="{% url 'inicio' %}" style="color: white; text-decoration: none;">Principal</a></li>
            <li><a href="{% url 'login' %}" style="color: white; text-decoration: none;">Login</a></li>
            <li><a href="{% url 'viaje' %}" style="color: white; text-decoration: none;">Viaje</a></li>
            <li><a href="{% url 'reg_user' %}" style="color: white; text-decoration: none;">Registro usuario</a></li>
            <li><a href="{% url 'registro' %}" style="color: white; text-decoration: none;">Registro</a></li>
            <li><a href="{% url 'reserva' %}" style="color: white; text-decoration: none;" >Reserva</a></li>
            <li><a href="{% url 'blog' %}" style="color: white; text-decoration: none;">Blog</a></li>
            {% if user.is_authenticated %}
            <li>
              <form action="{% url 'cerrar_sesion' %}" method="post">
                {% csrf_token %}
                <button type="submit" style="color: white; text-decoration: none; background: none; border: none; cursor: pointer;">Cerrar sesión</button>
              </form>
            </li>
            {% endif %}
          </ul>
        </div>
    </nav>
    <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1;">
          <div style="background-color: white; padding: 20px;">
            <h2>Hotel más alto de Dubai</h2>
            <img src="{% static 'img/hotelmasalto.jpeg' %}" alt="Hotel más alto de Dubai" style="width: 100%;">
            <p>En Dubai encontrarás algunos de los hoteles más altos y lujosos del mundo</p>
          </div>
        </div>
        <div style="flex: 1;">
          <div style="background-color: white; padding: 20px;">
            <h2>Archipiélago artificial en forma de mapamundi</h2>
            <img src="{% static 'img/mardubai.jpg' %}" alt="Archipiélago artificial en forma de mapamundi" style="width: 100%;">
            <p>Hay un archipiélago artificial en forma de mapamundi.</p>
          </div>
        </div>
    </div>
    <ul style="list-style: none; padding: 0;">
        <li style="background-color: #e0e0e0; padding: 20px;">
          <style>
            .circle {
                width: 100px; /* Ajusta el ancho deseado */
                height: 100px; /* Ajusta la altura deseada */
                border-radius: 50%; /* Hace que la imagen tenga forma de círculo */
            }
        </style>
        
        <img src="{% static 'img/l1.jpeg' %}" class="circle">
          <h3 style="margin: 0;">Habibi</h3>
          <p>¿Cómo es Dubai?</p>
          <p>Dubai es un lugar verdaderamente mágico y sorprendente. Dubai es una ciudad única que combina lujo, modernidad y cultura. Si te gusta disfrutar de las playas, las compras, los deportes extremos, la cultura, la arquitectura impresionante y la buena comida, ¡Dubai es definitivamente un lugar donde debes estar! Además, la gente es muy amable y acogedora.</p>
        </li>
        <li style="background-color: #f5f5f5; padding: 20px;">
          <style>
            .circle {
                width: 100px; /* Ajusta el ancho deseado */
                height: 100px; /* Ajusta la altura deseada */
                border-radius: 50%; /* Hace que la imagen tenga forma de círculo */
            }
        </style>
        
        <img src="{% static 'img/l3.jpeg' %}" class="circle">
          <h3 style="margin: 0;">Dubai_Lovers</h3>
          <p>Mi experiencia en Dubai</p>
          <p>¡Hola amigos/as!, ¡qué bueno verlos por aquí! Les voy a contar que mi experiencia en Dubai fue súper genial, me encantó todo. Además, la comida fue espectacular, ¡no saben las delicias que probé! Definitivamente, les recomiendo que si tienen la oportunidad de visitarlo, ¡no se lo pierdan! Les aseguro que no se arrepentirán. ¡Un abrazo fuerte!</p>
        </li>
        <li style="background-color: #e0e0e0; padding: 20px;">
          <style>
            .circle {
                width: 100px; /* Ajusta el ancho deseado */
                height: 100px; /* Ajusta la altura deseada */
                border-radius: 50%; /* Hace que la imagen tenga forma de círculo */
            }
        </style>
        
        <img src="{% static 'img/l2.jpeg' %}" class="circle">
          <h3 style="margin: 0;">Shamsa</h3>
          <p>Lo que me gustó de Dubai</p>
          <p>¡Hola amigo/a! Si hay algo que me encantó de Dubai, es que hay tantos lugares y atracciones turísticas que nunca te aburres, ¿sabes? Uno de mis sitios favoritos fue el famoso Burj Khalifa, ¡la vista desde arriba es impresionante! También fui a la Palm Jumeirah, que es una isla artificial con forma de palmera, ¡fue una experiencia única! Y si lo tuyo es la adrenalina, te recomiendo que visites el parque temático IMG Worlds of Adventure, ¡me lo pasé genial allí! Además, si te gusta ir de compras, el centro comercial Dubai Mall es simplemente espectacular, ¡es uno de los más grandes del mundo! En fin, hay lugares para todos los gustos, ¡no te aburrirás! Cuando decidas visitar este maravilloso destino, ¡nos vemos allí! ¡Un abrazo!</p>
        </li>
      </ul>
      <div style="display: flex; gap: 20px; margin-top: 20px;">
        <div style="flex: 1;">
          <label for="email">Escribe tu email</label>  
          <input id="email" type="email" class="validate" style="width: 100%;">
        </div>
        <a href="#!" class="input-field col 6 btn waves-effect waves-teal" style="background-color: #333; color: white; padding: 10px; text-decoration: none;">Enviar</a>
      </div>
    </div>
      <footer style="background-color: #333; color: white; padding: 20px; margin-top: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <div>
            <h5>Pié de Página</h5>
            <p>Nos alegra que visites nuestro sitio web. Acá te dejamos más contenido en línea relacionado al tema.</p>
          </div>
          <div>
            <h5>Enlaces</h5>
            <ul style="list-style: none; padding: 0; margin: 0;">
              <li><a href="https://youtu.be/SONsHnfPTG0?feature=shared" style="color: white; text-decoration: none;">10 Lugares imprescindibles</a></li>
              <li><a href="https://youtu.be/eZ99xQAbLRY?feature=shared" style="color: white; text-decoration: none;">10 atracciones más impresionantes</a></li>
            </ul>
          </div>
        </div>
      </footer>
</body>
</html>